title: Shirish Maharjan
logo: assets/img/Shirish Maharjan (1).jpg
description: Computer Engineer | Big Data Analyst | Data Enthusiast | AI Researcher
show_downloads: true
#theme: jekyll-theme-minimal
theme: minimal
